### PR TITLE
Merge new format fixes

### PR DESCRIPTION
**Pull request by jonweinb**
Implemented as discussed in:
https://github.com/emilyriehl/yoneda/pull/20
(Apologies for the earlier merging of the previous branch)

### CODE REVIEW

**Comment by fredrik-bakke** [comment]
I don't think there is any need for apologies!
I'm glad you are embracing the new working format, and hope my comments can be of help. To be honest, I feel I should apologize for initiating changes and not following through on them yet.

**Comment by jonweinb** [comment]
No worries, thank you for working through it @fredrik-bakke!

**Comment by emilyriehl** [comment]
Yes @fredrik-bakke please enjoy your holidays and ignore us continuing to putter away. We agree and are grateful for the stylistic conventions you've introduced, and have things under control ;)

**Comment by emilyriehl** [comment]
This all looks basically fine to me. I'm going to merge now so I can pull these changes into the pull request that I currently have open.

**Pull request merged**
