### PR TITLE
Naturality for Yoneda lemma

### PR DESCRIPTION
**Pull request by emilyriehl**
I don't recommend merging this now but wanted feedback from @fizruk. 

In this pull request I've

(a) added a proof that given a fiberwise equivalence `(a : A) -> Equiv (B a) (C a)` where `C` is a covariant family then `B` is too.

Using this, naturality of the evid and yon maps of the Yoneda lemma are formal consequences of `naturality-covariant-fiberwise-transformation`. (Note this is not the optimal formulation of these naturality statements. For that, we'll need to calculate the action by covariant transport in the family  `\ a -> (z : A) → hom A a z → C z`.)

The typechecking of `is-natural-in-object-evid` is slow but terminates within a few seconds. On machine, the typechecking of `is-natural-in-object-yon` has not terminated (and thus the construction might be wrong).

I'm curious what's going on here. Any insight would be welcome.

### CODE REVIEW

**Comment by fizruk** [comment]
I can confirm the problem reproduces for me as well. I'm not sure yet what exactly causes the computation to run this long (it did not finish within an hour on my machine), I will investigate and report back.

**Comment by emilyriehl** [comment]
Thanks. I'm offline this week so there's no rush. Also please go ahead and merge the other pull requests whenever they're ready without waiting for me to weigh in.

**Comment by fizruk** [comment]
The issue has been fixed in [rzk-0.5.4](https://github.com/rzk-lang/rzk/releases/tag/v0.5.4). I've rerun the jobs and now checks pass (and it also works fine on my machine).

The problem was with the strategy rzk used to unify terms.
In particular, here it had to unify

```
covariant-transport
  A a b f
  (\ (x : A) → (z : A) → (x₁ : hom A x z) → C z)
  (is-covariant-yoneda-domain A is-segal-A C is-covariant-C)
  (yon A is-segal-A a C is-covariant-C u)
```
and
```
covariant-transport
  A a b f
  (\ (x : A) → (z : A) → (x₁ : hom A x z) → C z)
  (is-covariant-yoneda-domain A is-segal-A C is-covariant-C)
  ((\ (x : A) → yon A is-segal-A x C is-covariant-C) a u)
```

As you can see, these terms are almost identical, except in the last argument.
Before the change/fix rzk would see that they are not identical and evaluate both terms before further unification. The change in https://github.com/rzk-lang/rzk/pull/76 switches the strategy to always try to decompose unification problems `f x =?= g y` into `f =?= g` and `x =?= y` first, and evaluate `f x` and `g y` only if unification via decomposition fails.

Although this change works (as you can see the GitHub Action checks now pass), I'm still not sure why evaluation of these transports took so long. I will look into it later to see if there is some sort of inefficiency/bug in the evaluator.

**Comment by fizruk** [comment]
I've resolved the conflicts and I think this is ready to be merged!

**Comment by emilyriehl** [comment]
Very interesting! Thanks for sorting this out @fizruk.

I'm not sure whether it makes sense to merge this first or the other pull request first so maybe I'll leave that to you.

**Comment by fizruk** [comment]
@fredrik-bakke would you mind if we merge this before #41? Perhaps, you want to apply some of the naming changes in this PR directly (to the definitions introduced here)?

**Comment by fizruk** [comment]
That is fine, take your time! :)

**Pull request merged**
