### PR TITLE
WIP Implement conventions

### PR DESCRIPTION
**Pull request by fredrik-bakke**
Progresses #14.

### CODE REVIEW

**Comment by fredrik-bakke** [comment]
Some more things I can note regarding your earlier refactoring, @emilyriehl:
- When line-breaking right after starting a lambda abstraction, i.e. after `->`, it is not necessary to increase the indentation level. Although, usually, lambda expressions should be placed in parentheses for readability, thus increasing the indentation level of the entire lambda expression.
- Variables like `fhasinverse` should be named `has-inverse-f` (although per an earlier discussion, I do possibly prefer `is-invertible`).
- When either argument of a pairing requires multiple lines, it is the convention to parenthesize both arguments.
  E.g. `something-short , something-much-much-longer`, when broken into two lines, should be
  
  ```rzk
  ( something-short) ,
  ( something-much-much-longer)
  ```
  The same goes for other binary operators as well.
- Indentation should always be in a multiple of the base indentation (in your case, 2 spaces). Also, remember to always wrap lines at the earliest possible branching point when you are wrapping lines. Otherwise, you will introduce excessively indented code. E.g. don't write
  ```rzk
  := \ x y -> my-function
               ( a x) (b y)
  ```
  but
    ```rzk
  :=
      \ x y ->
      my-function
        ( a x)
        ( b y)
  ```

**Comment by emilyriehl** [comment]
Merged by request.

**Comment by fizruk** [comment]
> Alright, that's probably as much as I will have time for today. Perhaps I will have a little more time next week to continue this work, although I won't promise anything. It is probably best, however, if this branch is merged quickly to avoid merge conflicts later on.
> 
> Note that the branch currently doesn't type check due to what I believe is [a bug with the `rzk` parser](https://github.com/fizruk/rzk/issues/63).

I will make a minor release of `rzk` fixing the problem with `title` attributes soon. No changes required in this repository.

**Comment by fizruk** [comment]
`rzk-v0.5.2` is out, but the build still fails. Apparently, not all names have been properly refactored. I will try to fix it now.

**Comment by fizruk** [comment]
I see that @emilyriehl has already fixed that in https://github.com/emilyriehl/yoneda/commit/e1b83c5d2739ffa622c20a1732207a4f03157148.

**Comment by fredrik-bakke** [comment]
Thanks both of you and sorry for the mess-up

**Pull request merged**
