### PR TITLE
Dependent yoneda

### PR DESCRIPTION
**Pull request by emilyriehl**
This adds a proof of the dependent Yoneda lemma and the lemmas that precede it. For this I needed to move the definition of initial objects into the Yoneda file. Later, I'll add the dual result and move final objects in there as well.

One naming question: I have a mild preference for the more grammatical 

```rzk
A-is-segal : is-segal A
```
rather than

```rzk
is-segal-A : is-segal A
```
because I think it means the proofs are slightly nicer to read. But if someone has feelings either way I'd like to hear about them.

### CODE REVIEW

**Comment by fizruk** [comment]
I do not have a strong preference regarding the naming. @fredrik-bakke what do you say?

**Comment by jonweinb** [comment]
I am sorry for closing this branch prematurely. I have reopened it so everyone can reply. I will be more aware of the workflow in the future. My sincere apologies again!

**Comment by emilyriehl** [comment]
Not a big deal at all. (And actually it's not clear to me what reopening a merged branch does? I think it's still merged.)

Personally I like the collaborative aspect of using pull requests because it makes it easy for everyone to comment on new code before it's officially merged. But of course we can always revise the code after merging instead so it really doesn't matter.

**Comment by fredrik-bakke** [comment]
The point of having the less grammatical `is-segal-A` is that names should closely imitate the type of the term. By following this scheme for variable names as well, we get more homogenous code with names that could perhaps be a bit easier to guess and interpret. Take for instance the theorem that should be named `is-segal-Σ`. Applying it to get a proof that `Σ A B` is Segal would look like `is-segal-Σ A B ...`. Similarly, the name of a hypothesis that the Sigma type is segal should have the form `is-segal-Σ-A-B`. Both of these would have type `is-segal (Σ A , B)`.

I think perhaps part of what may be bothering you at the moment is that most of the constructs have not yet been given proper names, making the true pattern unobvious and only highlighting the drawbacks of the scheme. I really wish I had the time to help you get everything in place at the moment, but I'm currently on vacation and won't be back in my office until the very end of July.

**Comment by jonweinb** [comment]
I think @fredrik-bakke has a point re the naming convention.

If we're deciding for it I could do some of the renaming.

**Comment by fredrik-bakke** [comment]
I'm open to renegotiate this in August. Rzk is not Agda, and I don't know precisely how the shoe will fit.

**Comment by emilyriehl** [comment]
No need. I've come around :)

**Pull request merged**
